🔧 add dependabot config (#99)
* 🔨 add houseKeeping script

* Create deploy-on-pi.yml

* 🔧 add dependabot config (#93)

Co-authored-by: Idriss MOHAMADY <pro.mohamady@gmail.com>

* ✅ dependabot update path

* Update dependabot.yml

* Update dependabot.yml

* Update dependabot.yml

* Update dependabot.yml

* Revert "Update dependabot.yml"

This reverts commit 2e7710e5b370c94ebabca5c50b6964de05a86ab0.

* Revert "Update dependabot.yml"

This reverts commit 3119cfae2632d766c41082e38dc2de7902e3097c.

* Revert "Update dependabot.yml"

This reverts commit e0dd0d1fecf1f3b94a8236fae0aed77bf0cace5a.

* Revert "Update dependabot.yml"

This reverts commit 10ada651016f0ec13034083ca47f56a7989d3dfa.

* Revert "✅ dependabot update path"

This reverts commit a2203691a2bb9e809eed8bd60de840d605a8af1f.

---------

Co-authored-by: Idriss MOHAMADY <pro.mohamady@gmail.com>

diff --git a/.github/workflows/deploy-on-pi.yml b/.github/workflows/deploy-on-pi.yml
--- a/.github/workflows/deploy-on-pi.yml
+++ b/.github/workflows/deploy-on-pi.yml
@@ -42,7 +42,7 @@ jobs:
 
       - name: Check if git pull was successful
         if: steps.ssh_pull.outcome == 'failure'
-        run: exit 1  # Fail the workflow if git pull failed
+        run: exit 1 # Fail the workflow if git pull failed
 
       - name: SSH to Raspberry Pi and restart Docker Compose
         id: ssh_compose
@@ -59,4 +59,4 @@ jobs:
 
       - name: Check if Docker Compose restart was successful
         if: steps.ssh_compose.outcome == 'failure'
-        run: exit 1  # Fail the workflow if Docker Compose restart failed
+        run: exit 1 # Fail the workflow if Docker Compose restart failed
