🔥 update action

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -39,7 +39,7 @@ jobs:
       - name: Set up Node.js 16
         uses: actions/setup-node@v3
         with:
-          node-version: '16'
+          node-version: "16"
 
       - name: Set up JDK 17
         uses: actions/setup-java@v4
@@ -84,3 +84,59 @@ jobs:
         uses: github/codeql-action/analyze@v2
         with:
           category: "/language:${{matrix.language}}"
+  deploy:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
+    environment: staging
+    env:
+      PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
+      PI_USERNAME: ${{ secrets.PI_USERNAME }}
+      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set SSH key permissions
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+
+      - name: Debug Environment Variables
+        run: |
+          echo "PUBLIC_IP: $PUBLIC_IP"
+          echo "PI_USERNAME: $PI_USERNAME"
+
+      - name: SSH to Raspberry Pi and pull changes
+        id: ssh_pull
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.PUBLIC_IP }}
+          username: ${{ secrets.PI_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            cd dev/projects/wadiag
+            git reset --hard origin/master
+            git pull origin master
+        continue-on-error: true
+
+      - name: Check if git pull was successful
+        if: steps.ssh_pull.outcome == 'failure'
+        run: exit 1 # Fail the workflow if git pull failed
+
+      - name: SSH to Raspberry Pi and restart Docker Compose
+        id: ssh_compose
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.PUBLIC_IP }}
+          username: ${{ secrets.PI_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            cd dev/projects/wadiag
+            docker-compose down
+            docker-compose up --build -d
+        continue-on-error: true
+
+      - name: Check if Docker Compose restart was successful
+        if: steps.ssh_compose.outcome == 'failure'
+        run: exit 1 # Fail the workflow if Docker Compose restart failed
